cmdbox/profiles/urls.py
from django.conf.urls import url

from cmdbox.profiles import views


urlpatterns = [
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^account/$', views.account, name='account'),
    url(r'^password/$', views.password, name='password'),
    url(r'^logins/$', views.logins, name='logins'),
]

cmdbox/scaffold_templates/urls.py
from django.conf.urls import url

from cmdbox.scaffold_templates import views


urlpatterns = [
    url(r'^$', views.scaffold_templates, name='list'),
    url(r'^(?P<slug>[^/]+)/$', views.details, name='details'),
    url(r'^(?P<slug>[^/]+)/add-file/$', views.add_file, name='add_file'),
    url(r'^(?P<slug>[^/]+)/add-folder/$', views.add_folder, name='add_folder'),
    url(r'^(?P<slug>[^/]+)/(?P<file_id>\d+)/add-file/$', views.add_children_file, name='add_children_file'),
    url(r'^(?P<slug>[^/]+)/(?P<file_id>\d+)/add-folder/$', views.add_children_folder,
        name='add_children_folder'),
    url(r'^(?P<slug>[^/]+)/(?P<file_id>\d+)/rename/$', views.rename_file, name='rename_file'),
    url(r'^(?P<slug>[^/]+)/(?P<file_id>\d+)/duplicate/$', views.duplicate_file, name='duplicate_file'),
    url(r'^(?P<slug>[^/]+)/(?P<file_id>\d+)/delete/$', views.delete_file, name='delete_file'),
    url(r'^(?P<slug>[^/]+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<slug>[^/]+)/edit/(?P<file_id>\d+)/$', views.edit_file, name='edit_file'),
    url(r'^(?P<slug>[^/]+)/delete/$', views.delete, name='delete'),
]

cmdbox/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from cmdbox.core import views as core_views
from cmdbox.snippets import views as snippets_views
from cmdbox.scaffold_templates import views as scaffold_templates_views


urlpatterns = [
    url(r'^$', core_views.home, name='home'),
    url(r'^oauth/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^login/$', auth_views.login, {'template_name': 'core/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^settings/', include('cmdbox.profiles.urls', namespace='settings')),
    url(r'^snippets/$', snippets_views.index, name='snippets'),
    url(r'^snippets/add/$', snippets_views.add, name='add_snippet'),
    url(r'^scaffold-templates/$', scaffold_templates_views.index, name='scaffold_templates'),
    url(r'^scaffold-templates/add/$', scaffold_templates_views.add, name='add_scaffold_template'),
    url(r'^help/', include('cmdbox.help.urls', namespace='help')),
    url(r'^(?P<username>[^/]+)/$', core_views.profile, name='profile'),
    url(r'^(?P<username>[^/]+)/snippets/', include('cmdbox.snippets.urls', namespace='snippets')),
    url(r'^(?P<username>[^/]+)/scaffold-templates/',
        include('cmdbox.scaffold_templates.urls', namespace='scaffold_templates')),
    url(r'', include('cmdbox.api.urls', namespace='api'))
]

cmdbox/profiles/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _

from cmdbox.profiles.gravatar import get_gravatar_url


class Profile(models.Model):
    user = models.OneToOneField(User)
    url = models.URLField(_('url'), null=True, blank=True)
    location = models.CharField(_('location'), max_length=255, null=True, blank=True)
    company = models.CharField(_('company'), max_length=255, null=True, blank=True)

    class Meta:
        db_table = 'profiles'
        verbose_name = _('profile')
        verbose_name_plural = _('profiles')

    def get_display_name(self):
        full_name = self.user.get_full_name()
        if full_name:
            return full_name
        else:
            return self.user.username

    def get_avatar(self, size=64):
        return get_gravatar_url(self.user.email, size)


class SSHKey(models.Model):
    user = models.ForeignKey(User, related_name='ssh_keys')
    label = models.CharField(_('label'), max_length=255)
    fingerprint = models.CharField(_('fingerprint'), max_length=255)
    key = models.TextField(_('key'), max_length=1000)
    added_on = models.DateTimeField(_('added on'), auto_now_add=True)
    last_used = models.DateTimeField(_('last used'), null=True, blank=True)

    class Meta:
        db_table = 'ssh_keys'
        ordering = ('label', )
        verbose_name = _('ssh key')
        verbose_name_plural = _('ssh keys')

cmdbox/profiles/forms.py
from django import forms
from django.contrib.auth.models import User

from cmdbox.profiles.models import Profile


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ChangeUsernameForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', )


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('url', 'location', 'company')

cmdbox/profiles/views.py
from social.apps.django_app.default.models import UserSocialAuth

from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AdminPasswordChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from django.db import transaction
from django.shortcuts import render, redirect
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User

from cmdbox.profiles.forms import UserForm, ProfileForm, ChangeUsernameForm


@login_required
@transaction.atomic
def profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, _('Your profile was successfully updated!'))
            return redirect('settings:profile')
        else:
            messages.error(request, _('Please correct the error below.'))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'profiles/profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })


@login_required
def account(request):
    # Create a new instance of user to avoid changing the request.user instance
    # before actually persisting the changes.
    user = User.objects.get(pk=request.user.pk)
    if request.method == 'POST':
        form = ChangeUsernameForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, _('Your username was successfully updated!'))
            return redirect('settings:account')
        else:
            messages.error(request, _('Please correct the error below.'))
    else:
        form = ChangeUsernameForm(instance=user)
    return render(request, 'profiles/account.html', {'form': form})


@login_required
def password(request):
    if request.user.has_usable_password():
        PasswordForm = PasswordChangeForm
    else:
        PasswordForm = AdminPasswordChangeForm

    if request.method == 'POST':
        form = PasswordForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, _('Your password was successfully updated!'))
            return redirect('settings:password')
        else:
            messages.error(request, _('Please correct the error below.'))
    else:
        form = PasswordForm(request.user)
    return render(request, 'profiles/change_password.html', {'form': form})


@login_required
def logins(request):
    try:
        github_login = request.user.social_auth.get(provider='github')
    except UserSocialAuth.DoesNotExist:
        github_login = None
    try:
        twitter_login = request.user.social_auth.get(provider='twitter')
    except UserSocialAuth.DoesNotExist:
        twitter_login = None

    can_disconnect = (request.user.social_auth.count() > 1 or request.user.has_usable_password())
    return render(request, 'profiles/logins.html', {
        'github_login': github_login,
        'twitter_login': twitter_login,
        'can_disconnect': can_disconnect
    })

cmdbox/profiles/templates/profiles/includes/menu.html
{% load i18n %}

<div class="list-group">
  <a href="{% url 'account_settings' %}" class="list-group-item{% if active == 'profile' %} active{% endif %}">
    {% trans 'Profile' %}
  </a>
  <a href="{% url 'change_password' %}" class="list-group-item{% if active == 'password' %} active{% endif %}">
    {% trans 'Change password' %}
  </a>
  <a href="{% url 'account_settings' %}" class="list-group-item{% if active == 'ssh_keys' %} active{% endif %}">
    {% trans 'SSH keys' %}
  </a>
</div>

cmdbox/profiles/templates/profiles/includes/menu_profile.html
{% load i18n %}

<h2>
  <img src="{{ page_user.profile.get_avatar }}" alt="{{ page_user.profile.get_display_name }}" class="img-circle">
  {% if page_user.get_full_name %}
    {{ page_user.get_full_name }} <small class="text-muted">({{ page_user.username }})</small>
  {% else %}
    {{ page_user.username }}
  {% endif %}
  <a href="{% url 'settings:profile' %}" role="button" class="btn btn-default btn-sm pull-right" style="margin-top: 16px">
    <span class="glyphicon glyphicon-pencil"></span> Edit profile
  </a>
</h2>
<ul class="profile-details">
  {% if page_user.email %}
    <li>
      <span class="glyphicon glyphicon-envelope"></span> {{ page_user.email }}
    </li>
  {% endif %}
  {% if page_user.profile.url %}
    <li>
      <a href="{{ page_user.profile.url }}" target="_blank">
        <span class="glyphicon glyphicon-globe"></span> {{ page_user.profile.url }}
      </a>
    </li>
  {% endif %}
  {% if page_user.profile.location %}
    <li>
      <span class="glyphicon glyphicon-map-marker"></span> {{ page_user.profile.location }}
    </li>
  {% endif %}
  {% if page_user.profile.company %}
    <li>
      <span class="glyphicon glyphicon-briefcase"></span> {{ page_user.profile.company }}
    </li>
  {% endif %}
</ul>
<ul class="nav nav-tabs">
  <li role="presentation"{% if active == 'snippets' %} class="active"{% endif %}>
    <a href="{% url 'snippets:list' page_user.username %}">
      {% trans 'Snippets' %}
      <span class="badge">{{ page_user.snippets.count }}</span>
    </a>
  </li>
  <li role="presentation"{% if active == 'scaffold_templates' %} class="active"{% endif %}>
    <a href="{% url 'scaffold_templates:list' page_user.username %}">
      {% trans 'Scaffold Templates' %}
      <span class="badge">{{ page_user.scaffoldtemplates.count }}</span>
    </a>
  </li>
</ul>

cmdbox/profiles/templates/profiles/includes/menu_settings.html
{% load i18n %}

<div class="list-group">
  <a href="{% url 'settings:profile' %}" class="list-group-item{% if active == 'profile' %} active{% endif %}">
    {% trans 'Profile' %}
  </a>
  <a href="{% url 'settings:account' %}" class="list-group-item{% if active == 'account' %} active{% endif %}">
    {% trans 'Account' %}
  </a>
  <a href="{% url 'settings:password' %}" class="list-group-item{% if active == 'password' %} active{% endif %}">
    {% trans 'Change password' %}
  </a>
  <a href="{% url 'settings:logins' %}" class="list-group-item{% if active == 'logins' %} active{% endif %}">
    {% trans 'My logins' %}
  </a>
  <a href="{% url 'settings:profile' %}" class="list-group-item{% if active == 'ssh_keys' %} active{% endif %}">
    {% trans 'SSH keys' %}
  </a>
</div>