cmdbox/scaffold_templates/urls.py
from django.conf.urls import url

from cmdbox.scaffold_templates import views


urlpatterns = [
    url(r'^$', views.scaffold_templates, name='list'),
    url(r'^(?P<slug>[^/]+)/$', views.details, name='details'),
    url(r'^(?P<slug>[^/]+)/add-file/$', views.add_file, name='add_file'),
    url(r'^(?P<slug>[^/]+)/add-folder/$', views.add_folder, name='add_folder'),
    url(r'^(?P<slug>[^/]+)/(?P<file_id>\d+)/add-file/$', views.add_children_file, name='add_children_file'),
    url(r'^(?P<slug>[^/]+)/(?P<file_id>\d+)/add-folder/$', views.add_children_folder,
        name='add_children_folder'),
    url(r'^(?P<slug>[^/]+)/(?P<file_id>\d+)/rename/$', views.rename_file, name='rename_file'),
    url(r'^(?P<slug>[^/]+)/(?P<file_id>\d+)/duplicate/$', views.duplicate_file, name='duplicate_file'),
    url(r'^(?P<slug>[^/]+)/(?P<file_id>\d+)/delete/$', views.delete_file, name='delete_file'),
    url(r'^(?P<slug>[^/]+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<slug>[^/]+)/edit/(?P<file_id>\d+)/$', views.edit_file, name='edit_file'),
    url(r'^(?P<slug>[^/]+)/delete/$', views.delete, name='delete'),
]

cmdbox/snippets/urls.py
from django.conf.urls import url

from cmdbox.snippets import views


urlpatterns = [
    url(r'add/$', views.add, name='add'),
    url(r'^(?P<username>[^/]+)/(?P<slug>[^/]+)/$', views.snippet, name='snippet'),
    url(r'^(?P<username>[^/]+)/(?P<slug>[^/]+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<username>[^/]+)/(?P<slug>[^/]+)/delete/$', views.delete, name='delete'),
]

cmdbox/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from cmdbox.core import views as core_views
from cmdbox.snippets import views as snippets_views
from cmdbox.scaffold_templates import views as scaffold_templates_views


urlpatterns = [
    url(r'^$', core_views.home, name='home'),
    url(r'^oauth/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^login/$', auth_views.login, {'template_name': 'core/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^settings/', include('cmdbox.profiles.urls', namespace='settings')),
    url(r'^snippets/$', snippets_views.index, name='snippets'),
    url(r'^snippets/add/$', snippets_views.add, name='add_snippet'),
    url(r'^scaffold-templates/$', scaffold_templates_views.index, name='scaffold_templates'),
    url(r'^scaffold-templates/add/$', scaffold_templates_views.add, name='add_scaffold_template'),
    url(r'^help/', include('cmdbox.help.urls', namespace='help')),
    url(r'^(?P<username>[^/]+)/$', core_views.profile, name='profile'),
    url(r'^(?P<username>[^/]+)/snippets/', include('cmdbox.snippets.urls', namespace='snippets')),
    url(r'^(?P<username>[^/]+)/scaffold-templates/',
        include('cmdbox.scaffold_templates.urls', namespace='scaffold_templates')),
    url(r'', include('cmdbox.api.urls', namespace='api'))
]

cmdbox/snippets/models.py
from __future__ import unicode_literals
from string import Formatter
import pyparsing

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone

from cmdbox.core.models import AbstractService


class Snippet(AbstractService):
    content = models.TextField(_('content'))

    class Meta:
        verbose_name = 'snippet'
        verbose_name_plural = 'snippets'
        unique_together = (('user', 'slug'), )
        ordering = ('-updated_at', )

    def __unicode__(self):
        return self.slug

    def get_cleaned_content(self):
        comment = pyparsing.nestedExpr('/*', '*/').suppress()
        cleaned_content = comment.transformString(self.content)
        return cleaned_content

    def get_params(self):
        formatter = Formatter()
        format_iterator = formatter.parse(self.get_cleaned_content())
        params = {
            'args': list(),
            'kwargs': set()
        }
        for _tuple in format_iterator:
            field_name = _tuple[1]
            if field_name is not None:
                if field_name == '':
                    params['args'].append(field_name)
                elif field_name.isdigit():
                    if field_name not in params['args']:
                        params['args'].append(field_name)
                else:
                    params['kwargs'].add(field_name)
        return params

    def use(self, args, kwargs):
        output = ''
        try:
            output = self.get_cleaned_content().format(*args, **kwargs)
            self.used += 1
            self.last_used = timezone.now()
            self.save()
        except ValueError:
            raise ValueError(_('[S02] Cannot switch from manual field specification to automatic field numbering.'))
        except IndexError:
            raise IndexError(_('[S03]'))
        except KeyError:
            raise KeyError(_('[S04]'))
        return output


class Review(models.Model):
    snippet = models.ForeignKey(Snippet, related_name='reviews')
    content = models.TextField(_('content'))
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    revision = models.PositiveIntegerField(_('revision'), default=1)

    class Meta:
        verbose_name = 'review'
        verbose_name_plural = 'reviews'
        ordering = ('-revision', )

    def __unicode__(self):
        return '{0} ({1})'.format(self.snippet.slug, self.revision)

cmdbox/core/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext_lazy as _

from cmdbox.core.validators import validate_forbidden_slug


class SignupForm(UserCreationForm):
    email = forms.EmailField(
        help_text='Not required. The email address will only be used for password reset.',
        max_length=254,
        required=False
    )

    class Meta:
        model = User
        fields = ('username', 'email')


class AbstractServiceCreateForm(forms.ModelForm):
    slug = forms.CharField(label=_('Name'), max_length=255, required=True, help_text=_('Required slug field.'))

    class Meta:
        fields = ['slug', 'description', 'visibility']

    def __init__(self, user, *args, **kwargs):
        super(AbstractServiceCreateForm, self).__init__(*args, **kwargs)
        self.instance.user = user
        self.fields['slug'].validators.append(validate_forbidden_slug)

    def clean(self):
        cleaned_data = super(AbstractServiceCreateForm, self).clean()
        user = self.instance.user
        slug = cleaned_data.get('slug')
        if user.snippets.filter(slug=slug).exists() or user.scaffoldtemplates.filter(slug=slug).exists():
            self.add_error('slug', _('A snippet or scaffold template with this name already exists.'))

cmdbox/snippets/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from cmdbox.snippets.models import Snippet
from cmdbox.core.forms import AbstractServiceCreateForm


class CreateSnippetForm(AbstractServiceCreateForm):
    description = forms.CharField(
        label=_('Description'),
        max_length=100,
        help_text=_('Give a brief description of what this snippet is about. Not required.'),
        required=False
    )

    class Meta(AbstractServiceCreateForm.Meta):
        model = Snippet


class EditSnippetForm(forms.ModelForm):
    class Meta:
        model = Snippet
        fields = ['content', ]

cmdbox/snippets/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.decorators.http import require_POST

from cmdbox.snippets.models import Snippet
from cmdbox.snippets.forms import CreateSnippetForm, EditSnippetForm


def index(request):
    return render(request, 'snippets/index.html')


@login_required
def add(request):
    if request.method == 'POST':
        form = CreateSnippetForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            return redirect('profile', request.user.username)
    else:
        form = CreateSnippetForm(request.user)
    return render(request, 'snippets/add.html', {'form': form})


def snippets(request, username):
    user = get_object_or_404(User, username__iexact=username)
    return render(request, 'snippets/list.html', {'page_user': user})


def details(request, username, slug):
    snippet = get_object_or_404(Snippet, user__username=username, slug=slug)
    return render(request, 'snippets/details.html', {'snippet': snippet})


@login_required
def edit(request, username, slug):
    snippet = get_object_or_404(Snippet, user__username=username, slug=slug)
    if request.method == 'POST':
        form = EditSnippetForm(request.POST, instance=snippet)
        if form.is_valid():
            snippet = form.save()
            return redirect('snippets:details', snippet.user.username, snippet.slug)
    else:
        form = EditSnippetForm(instance=snippet)
    return render(request, 'snippets/edit.html', {'form': form})


@login_required
@require_POST
def delete(request, username, slug):
    snippet = get_object_or_404(Snippet, user__username=username, slug=slug)
    snippet.delete()
    return redirect('profile', request.user.username)

cmdbox/snippets/templates/snippets/add.html
{% extends 'base.html' %}

{% load i18n static widget_tweaks %}

{% block javascript %}
  <script>
    $(function () {
      $("#name").keyup(function () {
        var text = $(this).val();
        var slug = $.cmdbox.slug(text);
        $(".slug-preview").text(slug);
        $("#id_slug").val(slug);
      });

      $("#form-create-snippet").submit(function () {
        $("#btn-create-snippet").text("Creating…");
        $("#btn-create-snippet").prop("disabled", true);
      });

    });
  </script>
{% endblock %}

{% block breadcrumb %}
  <li><a href="{% url 'snippets' %}">{% trans 'Snippets' %}</a></li>
  <li class="active">{% trans 'Add' %}</li>
{% endblock %}

{% block content_header %}
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h2>{% trans 'Add snippet' %}</h2>
    </div>
  </div>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <form method="post" id="form-create-snippet">
        {% csrf_token %}

        {% if form.non_field_errors %}
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-label="{% trans 'Close' %}">
              <span aria-hidden="true">&times;</span>
            </button>
            {% for error in form.non_field_errors %}
              <p>{{ error }}</p>
            {% endfor %}
          </div>
        {% endif %}

        {% for hidden in form.hidden_fields %}
          {{ hidden }}
        {% endfor %}

        <div class="form-group{% if form.slug.errors %} has-error{% endif %}">
          <label for="{{ form.slug.id_for_label }}" class="control-label">{{ form.slug.label }}</label>
          <div class="row">
            <div class="col-sm-5">
              <input type="text"
                     id="name"
                     class="form-control"
                     value="{{ form.slug.value|default_if_none:'' }}"
                     maxlength="{{ form.slug.field.max_length }}"
                     autofocus>
              {% render_field form.slug class='form-control' type='hidden' %}
            </div>
            <div class="col-sm-7">
              <span class="help-block">
                /{{ user.username }}/<strong class="slug-preview">{{ form.slug.value|default_if_none:'your-snippet' }}</strong>/
              </span>
            </div>
          </div>
          {% for error in form.slug.errors %}
            <span class="help-block">{{ error }}</span>
          {% endfor %}
          {% if form.slug.help_text %}
            <span class="help-block">{{ form.slug.help_text }}</span>
          {% endif %}
        </div>

        <div class="form-group{% if form.description.errors %} has-error{% endif %}">
          <label for="{{ form.description.id_for_label }}" class="control-label">{{ form.description.label }}</label>
          {% render_field form.description class='form-control' %}
          {% for error in form.description.errors %}
            <span class="help-block">{{ error }}</span>
          {% endfor %}
          {% if form.description.help_text %}
            <span class="help-block">{{ form.description.help_text }}</span>
          {% endif %}
        </div>

        <hr>
        {% with choices=form.instance.VISIBILITY_CHOICES %}
          <div class="form-group{% if form.visibility.errors %} has-error{% endif %}">
            <div class="radio">
              <label>
                <input type="radio"
                       name="visibility"
                       value="{{ choices.0.0|slugify }}"
                       {% if form.visibility.value|slugify == choices.0.0|slugify %} checked{% endif %}>
                {{ choices.0.1 }}
              </label>
            </div>
            <span class="help-block">{% trans 'Anyone can see this snippet.' %}</span>
            <div class="radio">
              <label>
                <input type="radio"
                       name="visibility"
                       value="{{ choices.1.0|slugify }}"
                       {% if form.visibility.value|slugify == choices.1.0|slugify %} checked{% endif %}>
                {{ choices.1.1 }}
              </label>
            </div>
            <span class="help-block">{% trans 'It\'s still public but won\'t be published in the CmdBox directories.' %}</span>
            <div class="radio">
              <label>
                <input type="radio"
                       name="visibility"
                       value="{{ choices.2.0|slugify }}"
                       {% if form.visibility.value|slugify == choices.2.0|slugify %} checked{% endif %}>
                {{ choices.2.1 }}
              </label>
            </div>
            <span class="help-block">{% trans 'Only you can see this snippet.' %}</span>
            {% for error in form.visibility.errors %}
              <span class="help-block">{{ error }}</span>
            {% endfor %}
          </div>
        {% endwith %}
        <hr>
        <div class="form-group">
          <button type="submit" id="btn-create-snippet" class="btn btn-primary btn-block">
            {% trans 'Create snippet' %}
          </button>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

cmdbox/snippets/templates/snippets/details.html
{% extends 'base.html' %}

{% load i18n static %}

{% block stylesheet %}
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/highlight/styles/xcode.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'snippets/css/snippets.css' %}">
{% endblock %}

{% block javascript %}
  <script src="{% static 'vendor/highlight/highlight.pack.js' %}"></script>
  <script>
    hljs.initHighlightingOnLoad();
    $(function () {
      $("[data-toggle='tooltip']").tooltip();
    });
  </script>
{% endblock %}

{% block breadcrumb %}
  {% include 'snippets/includes/breadcrumb.html' with snippet=snippet %}
  <li class="active">{{ snippet.slug }}</li>
{% endblock %}

{% block content_header %}
  {% include 'snippets/includes/header.html' with active='snippet_code' %}
{% endblock %}

{% block content %}
  <div class="panel panel-default panel-snippet">
    <div class="panel-heading">
      {% if user.is_authenticated and user == snippet.user %}
        <span class="pull-right">
          <a href="{% url 'snippets:edit' snippet.user.username snippet.slug %}" class="btn-snippet">
            <span class="glyphicon glyphicon-pencil"></span>
          </a>
          <a href="{% url 'snippets:delete' snippet.user.username snippet.slug %}" class="btn-snippet btn-delete">
            <span class="glyphicon glyphicon-trash"></span>
          </a>
        </span>
      {% endif %}
      <a href="{% url 'api:snippet' snippet.user.username snippet.slug %}">
        <span class="glyphicon glyphicon-link"></span>
        {% url 'api:snippet' snippet.user.username snippet.slug %}
      </a>
    </div>
    <div class="panel-body">
      <pre><code class="lang-python">{{ snippet.content }}</code></pre>
    </div>
    <div class="panel-footer">
      <button type="button" class="btn btn-default btn-sm">Copy snippet to clipboard</button>
      <button type="button" class="btn btn-default btn-sm">Copy endpoint to clipboard</button>
      <button type="button" class="btn btn-default btn-sm">Use in the web browser</button>
    </div>
  </div>
{% endblock %}

cmdbox/snippets/templates/snippets/edit.html
{% extends 'base.html' %}

{% load i18n static %}

{% block stylesheet %}
  <link rel="stylesheet" type="text/css" href="{% static 'snippets/css/snippets.css' %}">
{% endblock %}

{% block javascript %}
  <script src="{% static 'vendor/ace/ace.js' %}" type="text/javascript" charset="utf-8"></script>
  <script>
    var editor = ace.edit("content");
    editor.setTheme("ace/theme/clouds");
    editor.getSession().setMode("ace/mode/html");
    editor.getSession().setUseWrapMode(true);
  </script>
{% endblock %}

{% block breadcrumb %}
  {% include 'snippets/includes/breadcrumb.html' with snippet=form.instance %}
  <li><a href="{% url 'snippets:details' form.instance.user.username form.instance.slug %}">{{ form.instance.slug }}</a></li>
  <li class="active">Edit</li>
{% endblock %}

{% block content_header %}
  {% include 'snippets/includes/header.html' with active='snippet_code' snippet=form.instance %}
{% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <a href="{% url 'api:snippet' form.instance.user.username form.instance.slug %}">
          <span class="glyphicon glyphicon-link"></span>
          {% url 'api:snippet' form.instance.user.username form.instance.slug %}
        </a>
      </div>
      <div class="panel-body" style="padding: 0">
        <textarea name="content" class="hide">{{ form.instance.content }}</textarea>
        <div id="content" style="width: 100%; height: 350px;">{{ form.instance.content }}</div>
      </div>
      <div class="panel-footer">
        <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
        <a href="{% url 'snippets:details' form.instance.user.username form.instance.slug %}" class="btn btn-default">
          {% trans 'Discard changes' %}
        </a>
      </div>
    </div>
  </form>
{% endblock %}

cmdbox/snippets/templates/snippets/index.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans 'Snippets' %}{% endblock %}

{% block breadcrumb %}
  <li class="active">{% trans 'Snippets' %}</li>
{% endblock %}

{% block content_header %}
  <h2>{% trans 'Snippets' %}</h2>
{% endblock %}

{% block content %}

{% endblock %}

cmdbox/snippets/templates/snippets/list.html
{% extends 'base.html' %}

{% load humanize i18n %}

{% block title %}
  {% blocktrans trimmed with username=page_user.username %}
    Snippets - {{ username }}
  {% endblocktrans %}
{% endblock %}

{% block breadcrumb %}
  <li><a href="{% url 'profile' page_user.username %}">{{ page_user.profile.get_display_name }}</a></li>
  <li class="active">{% trans 'Snippets' %}</li>
{% endblock %}

{% block content_header %}
  {% include 'profiles/includes/menu_profile.html' with active='snippets' %}
{% endblock %}

{% block content %}
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">
        <div class="pull-right" style="margin-top: -5px">
          <button type="button" class="btn btn-link btn-sm" style="font-weight: bold; color: #555">{% trans 'All' %}</button>
          <button type="button" class="btn btn-link btn-sm">{% trans 'Public' %}</button>
          <button type="button" class="btn btn-link btn-sm">{% trans 'Unlisted' %}</button>
          <button type="button" class="btn btn-link btn-sm">{% trans 'Private' %}</button>
          <div class="btn-group">
            <button type="button"
                    class="btn btn-default btn-sm dropdown-toggle"
                    data-toggle="dropdown"
                    aria-haspopup="true"
                    aria-expanded="false">
              <span class="glyphicon glyphicon-sort-by-attributes"></span>
              {% blocktrans with order='name' %}Order by <strong>{{ order }}</strong>{% endblocktrans %}
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
              <li><a href="javascript:void(0);">{% trans 'name' %}</a></li>
              <li><a href="javascript:void(0);">{% trans 'stars' %}</a></li>
              <li><a href="javascript:void(0);">{% trans 'numbers of usage' %}</a></li>
              <li><a href="javascript:void(0);">{% trans 'last used' %}</a></li>
              <li class="divider"></li>
              <li>
                <a href="javascript:void(0);">
                  <span class="glyphicon glyphicon-check"></span> <strong>{% trans 'asc' %}</strong>
                </a>
                <a href="javascript:void(0);">
                  <span class="glyphicon glyphicon-unchecked"></span> {% trans 'desc' %}
                </a>
              </li>
            </ul>
          </div>
          <a href="{% url 'add_snippet' %}" class="btn btn-primary btn-sm">
            <span class="glyphicon glyphicon-plus"></span> {% trans 'Add' %}
          </a>
        </div>
        {% trans 'Your snippets' %}
      </h3>
    </div>
    <div class="panel-body">
      <div class="form-group has-feedback" style="margin-bottom: 0;">
        <input type="text" class="form-control" placeholder="Search for snippets…">
        <span class="glyphicon glyphicon-search form-control-feedback" aria-hidden="true"></span>
      </div>
    </div>
    <div class="list-group">
      {% for snippet in page_user.snippets.all %}
        <a href="{% url 'snippets:details' snippet.user.username snippet.slug %}"
           class="list-group-item{% if snippet.visibility == snippet.PRIVATE %} list-group-item-warning{% elif snippet.visibility == snippet.UNLISTED %} list-group-item-info %}{% endif %}">
          <div class="pull-right" style="margin-top: 11px;">
            {% if snippet.language %}
              <strong style="opacity:0.8">{{ snippet.language }}</strong>
            {% endif %}
            <small data-toggle="tooltip"
                   data-placement="top"
                   title="{% blocktrans with version=snippet.version %}Version {{ version }}{% endblocktrans %}"
                   data-container="body"
                   style="margin-left: 8px; cursor: help">
              <span class="glyphicon glyphicon-tag"></span> {{ snippet.version }}
            </small>
            <small data-toggle="tooltip"
                   data-placement="top"
                   title="{% blocktrans with stars=snippet.stars %}Stars {{ stars }}{% endblocktrans %}"
                   data-container="body"
                   style="margin-left: 8px; cursor: help">
              <span class="glyphicon glyphicon-star"></span> {{ snippet.stars }}
            </small>
            <small data-toggle="tooltip"
                   data-placement="top"
                   title="{% blocktrans with used=snippet.used %}Used {{ used }} times{% endblocktrans %}"
                   data-container="body"
                   style="margin-left: 8px; cursor: help">
              <span class="glyphicon glyphicon-flash"></span> {{ snippet.used }}
            </small>
          </div>
          <div style="margin-bottom: 5px">
            {% if snippet.visibility == snippet.PRIVATE %}
              <span class="glyphicon glyphicon-lock"></span>
            {% elif snippet.visibility == snippet.UNLISTED %}
              <span class="glyphicon glyphicon-eye-close"></span>
            {% endif %}
            {% if snippet.description %}<strong>{{ snippet.description }}</strong>{% endif %}
            <small>/{{ user.username }}/{{ snippet.slug }}/</small>
          </div>
          <small style="opacity:0.8">
            Last used {{ snippet.last_used|naturaltime|default_if_none:'never' }}
          </small>
        </a>
      {% endfor %}
    </div>
    <div class="panel-footer">
      {{ page_user.snippets.count }} snippets
    </div>
  </div>

  <ul class="pagination" style="margin-top: 0"> <li class="disabled"><a aria-label="Previous" href="#"><span aria-hidden="true">«</span></a></li> <li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li> <li><a href="#">2</a></li> <li><a href="#">3</a></li> <li><a href="#">4</a></li> <li><a href="#">5</a></li> <li><a aria-label="Next" href="#"><span aria-hidden="true">»</span></a></li> </ul>
{% endblock %}

cmdbox/snippets/templates/snippets/snippet.html
{% extends 'base.html' %}

{% load i18n static %}

{% block stylesheet %}
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/highlight/styles/xcode.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'snippets/css/snippets.css' %}">
{% endblock %}

{% block javascript %}
  <script src="{% static 'vendor/highlight/highlight.pack.js' %}"></script>
  <script>
    hljs.initHighlightingOnLoad();
    $(function () {
      $("[data-toggle='tooltip']").tooltip();
    });
  </script>
{% endblock %}

{% block content %}

  {% include 'snippets/includes/header.html' with active='snippet_code' %}

  <div class="panel panel-default panel-snippet">
    <div class="panel-heading">
      {% if user.is_authenticated and user == snippet.user %}
        <span class="pull-right">
          <a href="{% url 'snippets:edit' snippet.user.username snippet.slug %}" class="btn-snippet">
            <span class="glyphicon glyphicon-pencil"></span>
          </a>
          <a href="{% url 'snippets:delete' snippet.user.username snippet.slug %}" class="btn-snippet btn-delete">
            <span class="glyphicon glyphicon-trash"></span>
          </a>
        </span>
      {% endif %}
      <a href="{% url 'api:snippet' snippet.user.username snippet.slug %}">
        <span class="glyphicon glyphicon-link"></span>
        {% url 'api:snippet' snippet.user.username snippet.slug %}
      </a>
    </div>
    <div class="panel-body">
      <pre><code class="lang-python">{{ snippet.content }}</code></pre>
    </div>
    <div class="panel-footer">
      <button type="button" class="btn btn-default btn-sm">Copy snippet to clipboard</button>
      <button type="button" class="btn btn-default btn-sm">Copy endpoint to clipboard</button>
      <button type="button" class="btn btn-default btn-sm">Use in the web browser</button>
    </div>
  </div>

{% endblock %}