cmdbox/scaffold_templates/urls.py
from django.conf.urls import url

from cmdbox.scaffold_templates import views


urlpatterns = [
    url(r'^$', views.scaffold_templates, name='list'),
    url(r'^(?P<slug>[^/]+)/$', views.details, name='details'),
    url(r'^(?P<slug>[^/]+)/add-file/$', views.add_file, name='add_file'),
    url(r'^(?P<slug>[^/]+)/add-folder/$', views.add_folder, name='add_folder'),
    url(r'^(?P<slug>[^/]+)/(?P<file_id>\d+)/add-file/$', views.add_children_file, name='add_children_file'),
    url(r'^(?P<slug>[^/]+)/(?P<file_id>\d+)/add-folder/$', views.add_children_folder,
        name='add_children_folder'),
    url(r'^(?P<slug>[^/]+)/(?P<file_id>\d+)/rename/$', views.rename_file, name='rename_file'),
    url(r'^(?P<slug>[^/]+)/(?P<file_id>\d+)/duplicate/$', views.duplicate_file, name='duplicate_file'),
    url(r'^(?P<slug>[^/]+)/(?P<file_id>\d+)/delete/$', views.delete_file, name='delete_file'),
    url(r'^(?P<slug>[^/]+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<slug>[^/]+)/edit/(?P<file_id>\d+)/$', views.edit_file, name='edit_file'),
    url(r'^(?P<slug>[^/]+)/delete/$', views.delete, name='delete'),
]

cmdbox/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from cmdbox.core import views as core_views
from cmdbox.snippets import views as snippets_views
from cmdbox.scaffold_templates import views as scaffold_templates_views


urlpatterns = [
    url(r'^$', core_views.home, name='home'),
    url(r'^oauth/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^login/$', auth_views.login, {'template_name': 'core/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^settings/', include('cmdbox.profiles.urls', namespace='settings')),
    url(r'^snippets/$', snippets_views.index, name='snippets'),
    url(r'^snippets/add/$', snippets_views.add, name='add_snippet'),
    url(r'^scaffold-templates/$', scaffold_templates_views.index, name='scaffold_templates'),
    url(r'^scaffold-templates/add/$', scaffold_templates_views.add, name='add_scaffold_template'),
    url(r'^help/', include('cmdbox.help.urls', namespace='help')),
    url(r'^(?P<username>[^/]+)/$', core_views.profile, name='profile'),
    url(r'^(?P<username>[^/]+)/snippets/', include('cmdbox.snippets.urls', namespace='snippets')),
    url(r'^(?P<username>[^/]+)/scaffold-templates/',
        include('cmdbox.scaffold_templates.urls', namespace='scaffold_templates')),
    url(r'', include('cmdbox.api.urls', namespace='api'))
]

cmdbox/scaffold_templates/models.py
from __future__ import unicode_literals
import os.path
import re

import humanize

from django.db import models, transaction
from django.utils.translation import ugettext_lazy as _

from cmdbox.core.models import AbstractService
from cmdbox.scaffold_templates.validators import validate_folder


class ScaffoldTemplate(AbstractService):

    class Meta:
        verbose_name = _('scaffold template')
        verbose_name_plural = _('scaffold template')
        unique_together = (('user', 'slug'), )
        ordering = ('-updated_at', )

    def get_folders_dict(self):
        folder_set = self.files.filter(file_type=File.FOLDER).values()
        folders = dict()
        for folder in folder_set:
            folders[folder['id']] = folder
        return folders

    def list_files(self):
        folders = self.get_folders_dict()
        files = self.files.filter(file_type=File.FILE).select_related('folder')
        for _file in files:
            _file.build_path(folders)
        files = list(files)
        files.sort(key=lambda k: (os.path.dirname(k.path), os.path.basename(k.path)))
        return files


class File(models.Model):
    FILE = 1
    FOLDER = 2
    FILE_TYPES = (
        (FILE, _('file')),
        (FOLDER, _('folder'))
    )

    name = models.CharField(_('name'), max_length=255)
    extension = models.CharField(_('extension'), max_length=10, null=True, blank=True)
    size = models.PositiveIntegerField(_('size'), default=0)
    template = models.ForeignKey(ScaffoldTemplate, related_name='files')
    folder = models.ForeignKey('File', null=True, related_name='files', validators=[validate_folder, ])
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)
    updated_at = models.DateTimeField(_('updated at'), auto_now=True)
    file_type = models.PositiveSmallIntegerField(_('file type'), choices=FILE_TYPES, default=FILE)
    content = models.TextField(_('content'), null=True, blank=True)

    class Meta:
        ordering = ('-file_type', 'name', )
        verbose_name = _('file')
        verbose_name_plural = _('files')
        unique_together = (('template', 'folder', 'name'), )

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.file_type == File.FILE:
            self.extension = os.path.splitext(self.name)[1][1:].strip()[:10]
            self.calculate_size()
        else:
            self.extension = None
            self.content = None
        super(File, self).save(*args, **kwargs)

    def build_path(self, folders=None):
        if folders is None:
            folders = self.template.get_folders_dict()
        path = '{0}/{1}'.format(self.template.slug, self.name)
        depth = 0
        folder = self.folder
        if folder is not None:
            folder_id = folder.pk
            path = '{0}/{1}'.format(folders[folder_id]['name'], path)
            depth += 1
            while folders[folder_id]['folder_id'] is not None:
                folder_id = folders[folder_id]['folder_id']
                path = '{0}/{1}'.format(folders[folder_id]['name'], path)
                depth += 1
        self.path = path
        self.depth = depth
        return self.path

    def calculate_size(self):
        if self.content:
            self.size = len(self.content.encode('utf8'))
        else:
            self.size = 0

    def get_naturalsize(self):
        return humanize.naturalsize(self.size)

    def is_folder(self):
        return self.file_type == File.FOLDER

    def _get_name_parts(self):
        name, extension = os.path.splitext(self.name)
        if extension == '.' or len(extension) > 11 or re.compile(r'\s').search(extension):
            return (self.name, '')
        return (name, extension)

    def _cut_multiple_copy(self, base_name, copy_text):
        regex = copy_text + '[\s\d+]*$'
        m = re.compile(regex)
        search_result = m.search(base_name)
        if search_result:
            copy_part = search_result.group()
            return base_name[:-len(copy_part) - 1]
        return base_name

    def _generate_duplicate_name(self):
        base_name, extension = self._get_name_parts()
        base_copy_text = _('copy')
        base_name = self._cut_multiple_copy(base_name, base_copy_text)

        copy_text = ' {0}'.format(base_copy_text)
        copy_name = ''

        if base_name.endswith(copy_text):
            base_name = base_name[:-len(copy_text)]

        copy_number = 1
        while True:
            max_length = 255 - len(copy_text) - len(extension)
            copy_name = '{0}{1}{2}'.format(base_name[:max_length], copy_text, extension)

            if File.objects.filter(name=copy_name, template=self.template, folder=self.folder).exists():
                copy_number += 1
                copy_text = ' {0} {1}'.format(base_copy_text, copy_number)
            else:
                break

        self.name = copy_name

    def clone(self):
        new_file = File(
            name=self.name,
            extension=self.extension,
            size=self.size,
            template=self.template,
            folder=self.folder,
            file_type=self.file_type,
            content=self.content
        )
        return new_file

    def duplicate(self):
        with transaction.atomic():
            copy = self.clone()
            copy._generate_duplicate_name()
            copy.save()
            if copy.is_folder():
                template_files = self.template.files.select_related('folder').all()
                files_bulk = duplicate_files(template_files, self, copy)
                if files_bulk:
                    File.objects.bulk_create(files_bulk)
            return copy


def duplicate_files(files, old_folder, new_folder):
    children_files = filter(lambda f: f.folder == old_folder, files)
    files_bulk = list()
    if children_files:
        for old_file in children_files:
            new_file = old_file.clone()
            new_file.folder = new_folder
            if old_file.is_folder():
                new_file.save()
                files_bulk += duplicate_files(files, old_file, new_file)
            else:
                files_bulk.append(new_file)
    return files_bulk

cmdbox/core/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext_lazy as _

from cmdbox.core.validators import validate_forbidden_slug


class SignupForm(UserCreationForm):
    email = forms.EmailField(
        help_text='Not required. The email address will only be used for password reset.',
        max_length=254,
        required=False
    )

    class Meta:
        model = User
        fields = ('username', 'email')


class AbstractServiceCreateForm(forms.ModelForm):
    slug = forms.CharField(label=_('Name'), max_length=255, required=True, help_text=_('Required slug field.'))

    class Meta:
        fields = ['slug', 'description', 'visibility']

    def __init__(self, user, *args, **kwargs):
        super(AbstractServiceCreateForm, self).__init__(*args, **kwargs)
        self.instance.user = user
        self.fields['slug'].validators.append(validate_forbidden_slug)

    def clean(self):
        cleaned_data = super(AbstractServiceCreateForm, self).clean()
        user = self.instance.user
        slug = cleaned_data.get('slug')
        if user.snippets.filter(slug=slug).exists() or user.scaffoldtemplates.filter(slug=slug).exists():
            self.add_error('slug', _('A snippet or scaffold template with this name already exists.'))

cmdbox/scaffold_templates/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from cmdbox.scaffold_templates.models import ScaffoldTemplate, File
from cmdbox.core.forms import AbstractServiceCreateForm


class CreateScaffoldTemplate(AbstractServiceCreateForm):
    description = forms.CharField(
        label=_('Description'),
        max_length=100,
        help_text=_('Give a brief description of what this scaffold template is about. Not required.'),
        required=False
    )

    class Meta(AbstractServiceCreateForm.Meta):
        model = ScaffoldTemplate


class EditScaffoldTemplate(forms.ModelForm):
    class Meta:
        model = ScaffoldTemplate
        fields = '__all__'


class FileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ('name', )

    def clean(self):
        cleaned_data = super(FileForm, self).clean()
        template = self.instance.template
        folder = self.instance.folder
        name = cleaned_data.get('name')
        files = File.objects.filter(template=template, folder=folder, name=name)
        if self.instance.pk:
            files = files.exclude(pk=self.instance.pk)
        if files.exists():
            self.add_error(
                'name',
                _('The name <strong>"{0}"</strong> is already taken. Please choose a different name.').format(name)
            )


class EditFileContentForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ('content', )

cmdbox/scaffold_templates/templates/scaffold_templates/details.html
{% extends 'base.html' %}

{% load filewalker i18n static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'scaffold_templates/css/details.css' %}">
{% endblock %}

{% block javascript %}
  <script src="{% static 'scaffold_templates/js/details.js' %}"></script>
{% endblock %}

{% block breadcrumb %}
  <li><a href="{% url 'profile' scaffold_template.user.username %}">{{ scaffold_template.user.profile.get_display_name }}</a></li>
  <li><a href="{% url 'scaffold_templates:list' scaffold_template.user.username %}">{% trans 'Scaffold Templates' %}</a></li>
  <li class="active">{{ scaffold_template.slug }}</li>
{% endblock %}

{% block messages %}
  {{ block.super }}
  {% if scaffold_template.version == 0 %}
    {% include 'scaffold_templates/includes/draft_warning.html' %}
  {% endif %}
{% endblock %}

{% block content_header %}
  {% include 'scaffold_templates/includes/header.html' with active='files' %}
{% endblock %}

{% block content %}
  <div class="btn-group btn-group-justified" role="group" aria-label="File Wizard" style="margin-bottom: 20px">
    <a href="{% url 'scaffold_templates:details' scaffold_template.user.username scaffold_template.slug %}" class="btn btn-sm btn-primary">
      <span class="glyphicon glyphicon-unchecked"></span> {% trans 'File Structure' %}
    </a>
    <a href="{% url 'scaffold_templates:edit' scaffold_template.user.username scaffold_template.slug %}" class="btn btn-sm btn-default">
      <span class="glyphicon glyphicon-unchecked"></span> {% trans 'File Contents' %}
    </a>
    <a href="#" class="btn btn-sm btn-default">
      <span class="glyphicon glyphicon-unchecked"></span> {% trans 'Default Values' %}
    </a>
    <a href="#" class="btn btn-sm btn-default">
      <span class="glyphicon glyphicon-unchecked"></span> {% trans 'Review & Release' %}
    </a>
  </div>
  {% comment %}
  <div class="panel panel-info">
    <div class="panel-heading">
      <span class="glyphicon glyphicon-info-sign"></span> Define the File Structure
    </div>
    <div class="panel-body">
      <p>First define the file structure of the scaffold template. You may add files and folders.</p>
      <p>Create the files properly by adding the extension to the filename, so we can pick the correct syntax highlight in the next step.</p>
      <p>You can find more help resources <a href="">clicking here</a>.</p>
    </div>
  </div>
  {% endcomment %}

  <nav>
    <ul class="pager">
      <li class="previous disabled">
        <a href="#">
          <span aria-hidden="true">&larr;</span> {% trans 'Previous' %}
        </a>
      </li>
      <li class="next">
        <a href="{% url 'scaffold_templates:edit' scaffold_template.user.username scaffold_template.slug %}">
          {% trans 'Next' %} <span aria-hidden="true">&rarr;</span>
        </a>
      </li>
    </ul>
  </nav>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">
        <div class="pull-right" style="margin-top: -5px">
          <button type="button"
                  class="btn btn-primary btn-sm js-add-file"
                  data-url="{% url 'scaffold_templates:add_folder' scaffold_template.user.username scaffold_template.slug %}">
            <span class="glyphicon glyphicon-folder-close"></span>
            {% trans 'Add folder' %}
          </button>
          <button type="button"
                  class="btn btn-primary btn-sm js-add-file"
                  data-url="{% url 'scaffold_templates:add_file' scaffold_template.user.username scaffold_template.slug %}">
            <span class="glyphicon glyphicon-file"></span>
            {% trans 'Add file' %}
          </button>
        </div>
        <span class="glyphicon glyphicon-inbox"></span> {{ scaffold_template.slug }}
      </h3>
    </div>
    <table id="table-files" class="table table-hover">
      <thead>
        <tr>
          <th style="width: 50%">{% trans 'Name' %}</th>
          <th>{% trans 'Size' %}</th>
          <th>{% trans 'Date Modified' %}</th>
          <th>{% trans 'Date Added' %}</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% walk scaffold_template.files.all %}
      </tbody>
    </table>
    <div class="panel-footer">
      <span class="items-count">{{ scaffold_template.files.count }}</span> {% trans 'items' %}
    </div>
  </div>

  <nav>
    <ul class="pager">
      <li class="previous disabled">
        <a href="#">
          <span aria-hidden="true">&larr;</span> {% trans 'Previous' %}
        </a>
      </li>
      <li class="next">
        <a href="{% url 'scaffold_templates:edit' scaffold_template.user.username scaffold_template.slug %}">
          {% trans 'Next' %} <span aria-hidden="true">&rarr;</span>
        </a>
      </li>
    </ul>
  </nav>

  <div class="modal fade" id="modal-delete-file"></div>
{% endblock %}

cmdbox/scaffold_templates/templates/scaffold_templates/edit.html
{% extends 'base.html' %}

{% load i18n static %}

{% block stylesheet %}
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/highlight/styles/xcode.css' %}">
  <style type="text/css">
    .panel-file .panel-body {
      height: 200px;
      overflow: hidden;
      padding: 0;
  -webkit-transition: all 0.2s ease 0s;
     -moz-transition: all 0.2s ease 0s;
       -o-transition: all 0.2s ease 0s;
          transition: all 0.2s ease 0s;
    }

    .panel-file .panel-body.panel-body-empty {
      background-color: #f5f5f5;
      text-align: center;
      padding-top: 55px;
    }

    .panel-file .panel-body.panel-body-empty .glyphicon {
      font-size: 32px;
      color: #999;
    }

    .panel-file:hover {
      cursor: pointer;
    }

    .panel-file table {
      font-size: 12px;
    }

    .panel-file table tbody {
      color: #777;
    }

    .file-container {
  -webkit-transition: all 0.2s ease 0s;
     -moz-transition: all 0.2s ease 0s;
       -o-transition: all 0.2s ease 0s;
          transition: all 0.2s ease 0s;
    }

  </style>
{% endblock %}

{% block javascript %}
  <script src="{% static 'vendor/highlight/highlight.pack.js' %}"></script>
  <script type="text/javascript">
    hljs.initHighlightingOnLoad();
    $(function () {
      $(".panel-file").hover(function () {
        $(this).removeClass("panel-default").addClass("panel-primary");
      }, function () {
        $(this).removeClass("panel-primary").addClass("panel-default");
      });

      $(".panel-file").click(function () {
        location.href = $(this).attr("data-url");
        //var container = $(this).closest(".file-container");
        //$(container).removeClass().addClass("col-md-12");
        //$(container).css("width", "100%");
        //$(".panel-body", container).css("height", "400px");
      });

      $.fn.changeDisplay = function (displayOption) {
        if (displayOption === "grid") {
          $(".col-md-12", this).removeClass("col-md-12").addClass("col-md-6");
        }
        else {
          $(".col-md-6", this).removeClass("col-md-6").addClass("col-md-12");
        }
      };

      $("[name='files-display-options']").change(function () {
        var displayOption = $(this).val();
        $("#files-list").changeDisplay(displayOption);
        Cookies.set("files-display-options", displayOption);
      });

    });
  </script>
{% endblock %}

{% block breadcrumb %}
  <li><a href="{% url 'profile' scaffold_template.user.username %}">{{ scaffold_template.user.profile.get_display_name }}</a></li>
  <li><a href="{% url 'scaffold_templates:list' scaffold_template.user.username %}">{% trans 'Scaffold Templates' %}</a></li>
  <li class="active">{{ scaffold_template.slug }}</li>
{% endblock %}

{% block messages %}
  {{ block.super }}
  {% if scaffold_template.version == 0 %}
    {% include 'scaffold_templates/includes/draft_warning.html' %}
  {% endif %}
{% endblock %}

{% block content_header %}
  {% include 'scaffold_templates/includes/header.html' with active='files' %}
{% endblock %}

{% block content %}
  <div class="btn-group btn-group-justified" role="group" aria-label="File Wizard" style="margin-bottom: 20px">
    <a href="{% url 'scaffold_templates:details' scaffold_template.user.username scaffold_template.slug %}" class="btn btn-sm btn-primary">
      <span class="glyphicon glyphicon-ok"></span> {% trans 'File Structure' %}
    </a>
    <a href="{% url 'scaffold_templates:edit' scaffold_template.user.username scaffold_template.slug %}" class="btn btn-sm btn-primary">
      <span class="glyphicon glyphicon-unchecked"></span> {% trans 'File Contents' %}
    </a>
    <a href="#" class="btn btn-sm btn-default">
      <span class="glyphicon glyphicon-unchecked"></span> {% trans 'Default Values' %}
    </a>
    <a href="#" class="btn btn-sm btn-default">
      <span class="glyphicon glyphicon-unchecked"></span> {% trans 'Review & Release' %}
    </a>
  </div>

  {% comment %}
  <div class="panel panel-info">
    <div class="panel-heading">
      <span class="glyphicon glyphicon-info-sign"></span> Define the File Contents
    </div>
    <div class="panel-body">

    </div>
  </div>
  {% endcomment %}

  <nav>
    <ul class="pager">
      <li class="previous">
        <a href="{% url 'scaffold_templates:details' scaffold_template.user.username scaffold_template.slug %}">
          <span aria-hidden="true">&larr;</span> {% trans 'Previous' %}
        </a>
      </li>
      <li class="next">
        <a href="#">
          {% trans 'Next' %} <span aria-hidden="true">&rarr;</span>
        </a>
      </li>
    </ul>
  </nav>

  <div class="btn-group" data-toggle="buttons" style="margin-bottom: 20px">
    <label class="btn btn-default{% if files_display_option == 'grid' %} active{% endif %}">
      <input type="radio"
             name="files-display-options"
             id="file-display-grid"
             value="grid"
             autocomplete="off"{% if files_display_option == 'grid' %} checked{% endif %}>
      <span class="glyphicon glyphicon-th-large"></span>
    </label>
    <label class="btn btn-default{% if files_display_option == 'list' %} active{% endif %}">
      <input type="radio"
             name="files-display-options"
             id="file-display-list"
             value="list"
             autocomplete="off"{% if files_display_option == 'list' %} checked{% endif %}>
      <span class="glyphicon glyphicon-menu-hamburger"></span>
    </label>
  </div>

  <div id="files-list">
    <div class="row">
      {% for file in scaffold_template.list_files %}
        <div class="file-container {% if files_display_option == 'list' %}col-md-12{% else %}col-md-6{% endif %}">
          <div class="panel panel-default panel-file"
               data-url="{% url 'scaffold_templates:edit_file' scaffold_template.user.username scaffold_template.slug file.pk %}">
            <div class="panel-heading">
              <span class="glyphicon glyphicon-file"></span>
              {{ file.path }}
            </div>
            <table class="table table-condensed">
              <thead>
                <tr>
                  <th>Kind</th>
                  <th>Size</th>
                  <th>Date Modified</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>{{ file.extension }}</td>
                  <td>{{ file.get_naturalsize }}</td>
                  <td>{{ file.updated_at|date:"M j, Y, H:i" }}</td>
                </tr>
              </tbody>
            </table>
            {% if file.content %}
              <div class="panel-body">
                <pre><code>{{ file.content }}</code></pre>
              </div>
            {% else %}
              <div class="panel-body panel-body-empty">
                <span class="glyphicon glyphicon-file"></span>
                <h4>{% trans 'This file is empty. Click to edit.' %}</h4>
              </div>
            {% endif %}
          </div>
        </div>
        {% if forloop.counter|divisibleby:2 %}</div><div class="row">{% endif %}
      {% endfor %}
    </div>
  </div>

  <nav>
    <ul class="pager">
      <li class="previous">
        <a href="{% url 'scaffold_templates:details' scaffold_template.user.username scaffold_template.slug %}">
          <span aria-hidden="true">&larr;</span> {% trans 'Previous' %}
        </a>
      </li>
      <li class="next">
        <a href="#">
          {% trans 'Next' %} <span aria-hidden="true">&rarr;</span>
        </a>
      </li>
    </ul>
  </nav>

{% endblock %}

cmdbox/scaffold_templates/templates/scaffold_templates/index.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans 'Scaffold Templates' %}{% endblock %}

{% block breadcrumb %}
  <li class="active">{% trans 'Scaffold Templates' %}</li>
{% endblock %}

{% block content_header %}
  <h2>{% trans 'Scaffold Templates' %}</h2>
{% endblock %}

{% block content %}

{% endblock %}

cmdbox/scaffold_templates/templates/scaffold_templates/partial_file.html
{% load i18n %}

{% widthratio depth 1 24 as padding %}

{% spaceless %}
  <tr data-id="{{ file.pk }}"
      data-type="{{ file.get_file_type_display }}"
      data-parent="{% if file.folder %}{{ file.folder.pk }}{% endif %}"
      data-depth="{{ depth }}"
      data-expanded="true">
    <td style="padding-left: {{ padding|add:8 }}px">
      <span class="toggle-folder">
        {% if file.is_folder %}
          <span class="glyphicon glyphicon-triangle-bottom text-muted folder-expand-icon"></span>
        {% endif %}
      </span>
      {% if file.is_folder %}
        <span class="glyphicon glyphicon-folder-open file-icon"></span>
      {% else %}
        <span class="glyphicon glyphicon-file file-icon"></span>
      {% endif %}
      <a href="javascript:void(0);" class="file-name">{{ file.name }}</a>
    </td>
    <td class="text-right">
      <small class="text-muted">
        {% if file.is_folder %}
          --
        {% else %}
          {{ file.get_naturalsize }}
        {% endif %}
      </small>
    </td>
    <td>
      <small class="text-muted">{{ file.updated_at|date:"M j, Y, H:i" }}</small>
    </td>
    <td>
      <small class="text-muted">{{ file.created_at|date:"M j, Y, H:i" }}</small>
    </td>
    <td>
      <div class="dropdown">
        <a href="#" id="item-menu-{{ file.pk }}"
           class="dropdown-toggle"
           role="button"
           data-toggle="dropdown"
           aria-haspopup="true"
           aria-expanded="false">
          <span class="glyphicon glyphicon-option-horizontal text-muted"></span>
        </a>
        <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="item-menu-{{ file.pk }}">
          <li class="dropdown-header">{{ file.name }}</li>
          <li role="separator" class="divider"></li>
          {% if file.is_folder %}
            <li>
              <a href="javascript:void(0);"
                 class="js-add-file"
                 data-folder-id="{{ file.pk }}"
                 data-url="{% url 'scaffold_templates:add_children_folder' file.template.user.username file.template.slug file.pk %}">
                <span class="glyphicon glyphicon-folder-close"></span>
                {% trans 'Add folder' %}
              </a>
            </li>
            <li>
              <a href="javascript:void(0);"
                 class="js-add-file"
                 data-folder-id="{{ file.pk }}"
                 data-url="{% url 'scaffold_templates:add_children_file' file.template.user.username file.template.slug file.pk %}">
                <span class="glyphicon glyphicon-file"></span>
                {% trans 'Add file' %}
              </a>
            </li>
          {% endif %}
          <li>
            <a href="javascript:void(0);"
               class="js-duplicate-file"
               data-url="{% url 'scaffold_templates:duplicate_file' file.template.user.username file.template.slug file.pk %}">
              <span class="glyphicon glyphicon-duplicate"></span>
              {% trans 'Duplicate' %}
            </a>
          </li>
          <li role="separator" class="divider"></li>
          <li>
            <a href="javascript:void(0);"
               class="js-rename-file"
               data-folder-id="{{ file.pk }}"
               data-url="{% url 'scaffold_templates:rename_file' file.template.user.username file.template.slug file.pk %}">
              <span class="glyphicon glyphicon-pencil"></span>
              {% trans 'Rename' %}
            </a>
          </li>
          <li>
            <a href="javascript:void(0);"
               class="js-delete-file"
               data-url="{% url 'scaffold_templates:delete_file' file.template.user.username file.template.slug file.pk %}">
              <span class="glyphicon glyphicon-trash"></span>
              {% trans 'Delete' %}
            </a>
          </li>
        </ul>
      </div>
    </td>
  </tr>
{% endspaceless %}